import ProductCardModel from '../components/Shop/ProductCardModel';

export const fakeProducts: ProductCardModel[] = [
  {
    id: '1',
    name: 'Product 1',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 4,
  },
  {
    id: '2',
    name: 'Product 2',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 4,
  },
  {
    id: '3',
    name: 'Product 3',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 4,
  },
  {
    id: '4',
    name: 'Product 4',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 5,
  },
  {
    id: '5',
    name: 'Product 5',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 1,
  },
  {
    id: '6',
    name: 'Product 6',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 2,
  },
  {
    id: '7',
    name: 'Product 7',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 3,
  },
  {
    id: '8',
    name: 'Product 8',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 3.3,
  },
  {
    id: '9',
    name: 'Product 9',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 4,
  },
  {
    id: '10',
    name: 'Product 10',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 4.5,
  },
  {
    id: '11',
    name: 'Product 11',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 0,
  },
  {
    id: '12',
    name: 'Product 12',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 1,
  },
  {
    id: '13',
    name: 'Product 13',
    price: 10,
    image: 'https://picsum.photos/200/300',
    rating: 2,
  },
];
