#name: sonar workflow
#
#on:
#  push:
#    branches: [main, develop]
#
#jobs:
#  sonarqube:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js 16.x
#        uses: actions/setup-node@v2.2.0
#        with:
#          node-version: 16.x
#          cache: npm
#      - run: npm install --force
#      - run: npm run build
#      - name: SonarQube Scan
#        uses: sonarsource/sonarqube-scan-action@master
#        env:
#          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}